Repository emqx/neuron-dashboard, pull requests merged in 2023-09, with the labels that each got.

#557 Refactor(node setting): support `multiple` dynamic `variableds` instead of just one(#541)
  src/composables/config/useNodeConfig.ts
Labels: refactor

#556 Refactor(node setting): support `multiple` dynamic `variableds` instead of just one(#540)
  src/composables/config/useNodeConfig.ts
Labels: refactor

#561 Feat(south, template): the add `tags` api `timeout` increased by 100ms when `importing` tags by excel
  src/api/config.ts
  src/api/template.ts
  src/composables/config/useGroupList.ts
  src/composables/config/useTemplateGroupList.ts
  src/config/index.ts
  src/utils/http.ts
Labels: enhancement

#560 Feat(south, template): the add `tags` api `timeout` increased by 100ms when `importing` tags by excel
  src/api/config.ts
  src/api/template.ts
  src/composables/config/useGroupList.ts
  src/composables/config/useTemplateGroupList.ts
  src/config/index.ts
  src/utils/http.ts
Labels: enhancement

#559 Feat(tag, monitoring): support `BYTES` type and wirte BYTES value
  src/composables/config/useAddTagCommon.ts
  src/composables/config/useTagForm.ts
  src/composables/data/useDataMonitoring.ts
  src/composables/data/useWriteDataCheckNParse.ts
  src/composables/data/useWriteDataDialog.ts
  src/i18n/config.ts
  src/i18n/data.ts
  src/types/enums.ts
  src/utils/regexps.ts
  src/utils/utils.ts
  src/views/config/southDriver/components/EditTagDialog.vue
  src/views/config/southDriver/components/TagForm.vue
  src/views/config/southDriver/components/TagListForm.vue
  src/views/monitoring/components/WriteDialog.vue
Labels: enhancement

#558 Feat(tag, monitoring): support `BYTES` type and wirte BYTES value
  src/composables/config/useAddTagCommon.ts
  src/composables/config/useTagForm.ts
  src/composables/data/useDataMonitoring.ts
  src/composables/data/useWriteDataCheckNParse.ts
  src/composables/data/useWriteDataDialog.ts
  src/i18n/config.ts
  src/i18n/data.ts
  src/types/enums.ts
  src/utils/regexps.ts
  src/utils/utils.ts
  src/views/config/southDriver/components/EditTagDialog.vue
  src/views/config/southDriver/components/TagForm.vue
  src/views/config/southDriver/components/TagListForm.vue
  src/views/monitoring/components/WriteDialog.vue
Labels: enhancement

#562 Refactor(north group): refactor `gewu` plugin name and its display (#536)
  src/composables/config/useDriver.ts
Labels: refactor

#563 Refactor(north group): refactor `gewu` plugin name and its display (#537)
  src/composables/config/useDriver.ts
Labels: refactor

#569 Refactor(license): modify error message when upload `License` failed
  src/i18n/error.ts
  src/utils/constants.ts
Labels: refactor

#568 Refactor(license): modify error message when upload `License` failed
  src/i18n/error.ts
  src/utils/constants.ts
Labels: refactor

#567 Refactor(node statistics): modify `statistics` icon
  src/assets/fonts/iconfont.css
  src/assets/images/statistics.png
  src/styles/index.scss
  src/views/config/northDriver/Index.vue
  src/views/config/northDriver/components/SetupItemCard.vue
  src/views/config/southDriver/Index.vue
  src/views/config/southDriver/components/SouthDriveItemCard.vue
Labels: refactor

#566 Refactor(node statistics): modify `statistics` icon
  src/assets/fonts/iconfont.css
  src/assets/images/statistics.png
  src/styles/index.scss
  src/views/config/northDriver/Index.vue
  src/views/config/northDriver/components/SetupItemCard.vue
  src/views/config/southDriver/Index.vue
  src/views/config/southDriver/components/SouthDriveItemCard.vue
Labels: refactor

#565 Feat(node statistic): `statistic` support `i18n`(#518)
  src/i18n/config.ts
Labels: enhancement

#564 Feat(node statistic): `statistic` support `i18n` (#517)
  src/i18n/config.ts
Labels: enhancement

#571 Refactor(north group): rename `gewu` plugin name (#537)
  src/composables/config/useDriver.ts
Labels: refactor

#570 Refactor(north group): rename `gewu` plugin name (#536)
  src/composables/config/useDriver.ts
Labels: refactor

#572 Feat(north group): `mqtt` and `gewu` plugin support edit group
  src/api/config.ts
  src/composables/config/useSubscription.ts
  src/composables/data/useWriteDataCheckNParse.ts
  src/types/config.d.ts
  src/views/config/components/DriverListSelector.vue
  src/views/config/components/GroupListSelector.vue
  src/views/config/northDriver/Group.vue
  src/views/config/northDriver/components/EditSubcriptionGroup.vue
Labels: enhancement

#575 Refactor(license tip): refactor `License` warning tips
  package.json
  src/components/LicenseTipDialog.vue
  src/composables/useCheckLicense.ts
  src/views/config/southDriver/Index.vue
  yarn.lock
Labels: refactor

#574 Refactor(license tip): refactor `License` warning tips
  package.json
  src/components/LicenseTipDialog.vue
  src/composables/useCheckLicense.ts
  src/views/config/southDriver/Index.vue
  yarn.lock
Labels: refactor

#573 Feat(north group): `mqtt` and `gewu` plugin support edit group
  src/api/config.ts
  src/composables/config/useSubscription.ts
  src/composables/data/useWriteDataCheckNParse.ts
  src/types/config.d.ts
  src/views/config/components/DriverListSelector.vue
  src/views/config/components/GroupListSelector.vue
  src/views/config/northDriver/Group.vue
  src/views/config/northDriver/components/EditSubcriptionGroup.vue
Labels: enhancement

#576 Refactor(license tip): refactor `License` warning tips
  package.json
  src/components/LicenseTipDialog.vue
  src/composables/useCheckLicense.ts
  src/views/config/southDriver/Index.vue
  yarn.lock
Labels: refactor

#580 Fixed(south, template): not getting list when `import tags `error (#577)
  src/composables/config/useGroupList.ts
  src/composables/config/useUploadTagList.ts
Labels: bug

#579 Fixed(south group): add `validate` for tags excel when `import tags` file
  src/App.vue
  src/composables/config/useAddTagCommon.ts
  src/composables/config/useGroupList.ts
  src/composables/config/useTemplateGroupList.ts
  src/composables/config/useUploadTagList.ts
  src/i18n/config.ts
  src/views/config/southDriver/Group.vue
  src/views/config/template/Group.vue
Labels: bug

#578 Fixed(south group): add `validate` for tags excel when `import tags` file
  src/App.vue
  src/composables/config/useAddTagCommon.ts
  src/composables/config/useGroupList.ts
  src/composables/config/useTemplateGroupList.ts
  src/composables/config/useUploadTagList.ts
  src/i18n/config.ts
  src/views/config/southDriver/Group.vue
  src/views/config/template/Group.vue
Labels: bug

#581 fix(useCheckLicense.ts): fix that can't display license tips when use…
  src/components/LicenseTipDialog.vue
  src/composables/useCheckLicense.ts
  src/views/config/southDriver/Index.vue
Labels: bug

#582 fix(useSubscription.ts): name can only contain numbers and letters
  src/composables/config/useSubscription.ts
  src/i18n/config.ts
  src/views/config/components/SouthGroupsCheckbox.vue
Labels: bug

#583 refactor(useSubscription.ts): only check device name
  src/composables/config/useSubscription.ts
  src/i18n/config.ts
Labels: refactor
